### ISSUE TITLE
about the model weight on hm3d

### ISSUE THREAD

**Issue by KarelZhang** [Ram81/habitat-imitation-baselines#14]
hi @Ram81 ,
Do you have the model weight based on hm3d dataset?
If you do, can you share with us?
Thanks!

**Comment by Ram81** [comment]
Hi @KarelZhang , you can look at [PIRLNav](https://github.com/Ram81/pirlnav#reproducing-results). It has imitation and RL finetuning results on HM3D. The policy architecture used it different but you can use the data provided as part of PIRLNav release to train policy architecture used in Habitat-Web

**Comment by Ram81** [comment]
Closing this issue as it is resolved
