### ISSUE TITLE
Is the shared semantic segmentation model the right one?

### ISSUE THREAD

**Issue by yimengli46** [Ram81/habitat-imitation-baselines#5]
Hi Ram,

The config file says the rednet_ckpt to use for running on a single node is `rednet_semmap_mp3d_40_v2_vince.pth`.
But the shared link for the semantic segmentation model is `rednet_semmap_mp3d_tuned.pth`.

Can you share the model weights named `rednet_semmap_mp3d_40_v2_vince.pth`?

**Comment by Ram81** [comment]
Hi @yimengli46, the semantic predictor checkpoint that is released is the same. The file names in the config were pointing to incorrect one. I have updated the configs in latest master. Let me know if you face similar issues.

**Comment by yimengli46** [comment]
Thank you for the quick response.
