### ISSUE TITLE
Question about reading the code.

### ISSUE THREAD

**Issue by yimengli46** [Ram81/habitat-imitation-baselines#7]
Hi Ram,

I have some questions about the code that I hope you can enlighten me.
BTW, the code quality is excellent, totally industry level.

What is the difference between `env_based` and `il_based` when you named the folders in `habitat_baselines/il`?

You seem to be using the `registry` pattern a lot. It's great for polymorphism, but I'm not very good at reading the code.
Would you tell me where you learned how to write code like that?
And the `trainer.eval()` in `run.py` is calling the `eval()` in `BaseTrainer` class right?

**Comment by Ram81** [comment]
Hi @yimengli46, 

Apologies for the late reply.

>BTW, the code quality is excellent, totally industry level.

Thanks a lot :)

>What is the difference between env_based and il_based when you named the folders in habitat_baselines/il?

The `env_based` training setup replays the demonstrations on the fly to collect data for imitation learning training. This requires a simulator in loop and allows us to scale training to > 16 GPUs without disk I/O bottlenecks.

The `disk_based` training setup stores the observations and actions from the demonstrations on the disk, which is generated once before training, and uses the data stored on disk to train agents using imitation learning. 

We used code in `env_based` setup for our ObjectNav training as it was faster and we used the `disk_based` code for our Pick&Place task as the it was faster to save the data on disk  and use that for training.

>You seem to be using the registry pattern a lot. It's great for polymorphism, but I'm not very good at reading the code.
> Would you tell me where you learned how to write code like that?

Our codebase borrows a large chunk from [habitat-lab](https://github.com/facebookresearch/habitat-lab), you can refer to the original repository for the structure and the abstraction. I built our project on top of habitat-lab and used the same for release.  I hope that answers your question.

>And the trainer.eval() in run.py is calling the eval() in BaseTrainer class right?

Yes, the trainer.eval() calls the eval() method of a class that inherits the `BaseTrainer`

Let me know if you have any other questions, I'll be happy to answer them :)

**Comment by yimengli46** [comment]
Thank you for the response, Ram. 
It cleared out all my confusion about the code.

**Comment by Ram81** [comment]
Great!

Closing this issue as it is resolved
