### ISSUE TITLE
Problem when running code on headless systems

### ISSUE THREAD

**Issue by anavuongdin** [Ram81/habitat-imitation-baselines#9]
Hi @Ram81,
First of all, as a student in this field, I feel grateful for your contribution. I was trying to build some imitation learning model in Habitat just like your paper.
However, when I cloned your code and ran it on a headless system. It encountered a problem as follows:
`DISPLAY not detected. For headless systems, compile with --headless for EGL support`

It seems that the problem appeared to be running with headless system. I had installed Habitat-sim with both headless/non-headless options but it failed at this very same stage.
Could you please tell me what possible problem I has encountered? Thank you in advance!

**Comment by Ram81** [comment]
@anavuongdin can you share the build command you executed to build with headless mode?

**Comment by anavuongdin** [comment]
I build the system with the instruction codes:
`./build.sh --bullet`
and
`./build.sh --headless --bullet`
I tried both options but they still ended with the same result (each time, I installed a new environment).

**Comment by anavuongdin** [comment]
Nevermind, I managed to fix this, this is according to improper installation of Habitat package due to the command:
`python setup.py develop --all`

**Comment by anavuongdin** [comment]
Hi @Ram81,
Good news is that I was able to run the training code for the Object-Nav task. However, new problem had arisen, for convenient, I want to reopen this thread to ask you.

> W1222 04:15:19.783210 633390 AttributesManagerBase.h:198] AttributesManager::loadAllConfigsFromPath : Parsin
g Object : Cannot find data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl or data/assets/objects/yc
b_google_16k_v2/configs_gltf/024_bowl.object_config.json. Aborting parse.

It seems that `data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl` was missing. Could you help me to solve this problem? Thank you.

**Comment by anavuongdin** [comment]
Furthermore, when I ran:
`python habitat_baselines/run.py --exp-config habitat_baselines/config/pickplace/il_pickplace.yaml --run-type eval EVAL_CKPT_PATH_DIR data/old_checkpoints/pick_place/pick_place_rgbd_new_inits.ckpt`
to evaluate the checkpoint you provided for the Pick and Place task, the following error occured:

>   2022-12-22 08:57:07,104 Initializing dataset PickPlaceDataset-v0
Traceback (most recent call last):
  File "habitat_baselines/run.py", line 79, in <module>
    main()
  File "habitat_baselines/run.py", line 40, in main    run_exp(**vars(args))  File "habitat_baselines/run.py", line 75, in run_exp
    execute_exp(config, run_type)
  File "habitat_baselines/run.py", line 60, in execute_exp
    trainer.eval()
  File "/.../habitat-web-baselines/habitat_baselines/common/base_trainer.py", line 111, in eval
    checkpoint_index=ckpt_idx,
  File "/.../habitat-web-baselines/habitat_baselines/il/disk_based/il_trainer.py", line 403, in _eval_checkpoint
    self.envs = construct_envs(config, get_env_class(config.ENV_NAME))
  File ".../habitat-web-baselines/habitat_baselines/utils/env_utils.py", line 59, in construct_envs
    scenes = dataset.get_scenes_to_load(config.TASK_CONFIG.DATASET)
  File "/.../habitat-web-baselines/habitat/core/dataset.py", line 122, in get_scenes_to_load
    assert cls.check_config_paths_exist(config)  # type: ignore[attr-defined]
AssertionError


It seemed that the data path `data/datasets/object_rearrangement/v3/{split}/{scene_split}.db` was missing. I was searching for this dataset throughout your repository and Habitat site but I couldn't find anything. Could you please help me with this issue? Many thanks in advance!

**Comment by anavuongdin** [comment]
> Hi @Ram81, Good news is that I was able to run the training code for the Object-Nav task. However, new problem had arisen, for convenient, I want to reopen this thread to ask you.
> 
> > W1222 04:15:19.783210 633390 AttributesManagerBase.h:198] AttributesManager::loadAllConfigsFromPath : Parsin
> > g Object : Cannot find data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl or data/assets/objects/yc
> > b_google_16k_v2/configs_gltf/024_bowl.object_config.json. Aborting parse.
> 
> It seems that `data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl` was missing. Could you help me to solve this problem? Thank you.

It looks like in your code, there is a file `habitat/datasets/object_nav/create_objectnav_dataset.py` that generates `ycb_google` objects. 
Does this automatically run when we train the model or we have to manually run this before training? Thank you!

**Comment by Ram81** [comment]
Hi @anavuongdin , did you download the object dataset from [here](https://github.com/Ram81/habitat-imitation-baselines#downloading-object-assets)?

**Comment by Ram81** [comment]
>It seemed that the data path data/datasets/object_rearrangement/v3/{split}/{scene_split}.db was missing. I was searching for this dataset throughout your repository and Habitat site but I couldn't find anything. Could you please help me with this issue? Many thanks in advance!

Hi @anavuongdin, thanks for pointing out. The instructions to generate the pick and place task dataset and running training script is missing in readme. I will work on adding the documentation for the same this week. Till then you can look at [this script](https://github.com/Ram81/habitat-imitation-baselines/blob/master/scripts/dataset/generate_pickplace_dataset.py), it generates a `lmdb` by replaying the pick and place demonstrations.  You can then use the path of the generated dataset [here](https://github.com/Ram81/habitat-imitation-baselines/blob/master/habitat_baselines/config/pickplace/il_pickplace.yaml#L22) to run training.

Let me know if you have any questions.

**Comment by anavuongdin** [comment]
> Hi @anavuongdin , did you download the object dataset from [here](https://github.com/Ram81/habitat-imitation-baselines#downloading-object-assets)?

Yes, I downloaded from that. The link [objectnav_mp3d_gibson_80k.json.gz](https://habitat-on-web.s3.amazonaws.com/release/datasets/objectnav/objectnav_mp3d_gibson_80k.zip) can not be accessed to. Also, I downloaded test_objects in https://habitat-on-web.s3.amazonaws.com/release/datasets/pick_place/objects.zip as you mentioned.

**Comment by Ram81** [comment]
Hi @anavuongdin, are you still facing this issue?

**Comment by me-no-money** [comment]
> > Hi @Ram81, Good news is that I was able to run the training code for the Object-Nav task. However, new problem had arisen, for convenient, I want to reopen this thread to ask you.
> > > W1222 04:15:19.783210 633390 AttributesManagerBase.h:198] AttributesManager::loadAllConfigsFromPath : Parsin
> > > g Object : Cannot find data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl or data/assets/objects/yc
> > > b_google_16k_v2/configs_gltf/024_bowl.object_config.json. Aborting parse.
> > 
> > 
> > It seems that `data/assets/objects/ycb_google_16k_v2/configs_gltf/024_bowl` was missing. Could you help me to solve this problem? Thank you.
> 
> It looks like in your code, there is a file `habitat/datasets/object_nav/create_objectnav_dataset.py` that generates `ycb_google` objects. Does this automatically run when we train the model or we have to manually run this before training? Thank you!

Hi @anavuongdin, have you solved the problem? I'm facing the same problem. Can you share the solution?

**Comment by Ram81** [comment]
Closing this issue as it is resolved in #12 .

**Comment by yvfengZhong** [comment]
Hello,

I wanted to share some insights regarding the ycb_google_16k_v2 directory setup. It appears that this directory corresponds directly to the ycb directory, and the ycb_google_16k_v2/configs_gltf aligns with the ycb/configs directory. Here's how you can set it up:

Linking and Renaming the Directory:

After downloading the YCB dataset, you can link the ycb directory to the data/assets/objects directory and rename it to ycb_google_16k_v2.
Renaming the Configs Directory:

Within the ycb directory, rename the configs directory to configs_gltf.
No Need to Alter Other Directories:

The collision_meshes and meshes directories can remain unchanged.
I hope this helps streamline your setup process. If anyone else has further insights or suggestions, feel free to add!
